Universe        = vanilla
Executable      = ./condor.sh
Requirements    = (CPU_Speed >= 1)
Rank		= CPU_Speed
request_memory  = 1800M
request_cpus    = 1
Priority        = 4
GetEnv          = True
Initialdir      = /star/u/kabir/GIT/BrightSTAR
Input           = /dev/null
Output          = /star/u/kabir/GIT/BrightSTAR/jobOutput/condor_job$(Process)_$RANDOM_INTEGER(0, 10000, 1).out
Error           = /star/u/kabir/GIT/BrightSTAR/jobOutput/condor_job$(Process)_$RANDOM_INTEGER(0, 10000, 1).err
Log             = /star/u/kabir/GIT/BrightSTAR/jobOutput/condor_job$(Process)_$RANDOM_INTEGER(0, 10000, 1).log
#Notify_user     = kabir@bnl.gov
#should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
+Experiment     = "star"
+Job_Type       = "cas"
Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/080/16080002/st_fms_16080002_raw_0000003.MuDst.root	/star/u/kabir/GIT/BrightSTAR/jobResults/RunFmsTreeMaker_16080002_0.root"
Queue

Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/080/16080002/st_fms_16080002_raw_1000002.MuDst.root	/star/u/kabir/GIT/BrightSTAR/jobResults/RunFmsTreeMaker_16080002_1.root"
Queue

Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/080/16080002/st_fms_16080002_raw_1500002.MuDst.root	/star/u/kabir/GIT/BrightSTAR/jobResults/RunFmsTreeMaker_16080002_2.root"
Queue

Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/080/16080002/st_fms_16080002_raw_2000003.MuDst.root	/star/u/kabir/GIT/BrightSTAR/jobResults/RunFmsTreeMaker_16080002_3.root"
Queue

Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/080/16080002/st_fms_16080002_raw_2500001.MuDst.root	/star/u/kabir/GIT/BrightSTAR/jobResults/RunFmsTreeMaker_16080002_4.root"
Queue

Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/080/16080002/st_fms_16080002_raw_2500016.MuDst.root	/star/u/kabir/GIT/BrightSTAR/jobResults/RunFmsTreeMaker_16080002_5.root"
Queue

Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/080/16080002/st_fms_16080002_raw_3000001.MuDst.root	/star/u/kabir/GIT/BrightSTAR/jobResults/RunFmsTreeMaker_16080002_6.root"
Queue

Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/080/16080002/st_fms_16080002_raw_4000006.MuDst.root	/star/u/kabir/GIT/BrightSTAR/jobResults/RunFmsTreeMaker_16080002_7.root"
Queue

Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/080/16080002/st_fms_16080002_raw_4500002.MuDst.root	/star/u/kabir/GIT/BrightSTAR/jobResults/RunFmsTreeMaker_16080002_8.root"
Queue

Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/080/16080002/st_fms_16080002_raw_4500018.MuDst.root	/star/u/kabir/GIT/BrightSTAR/jobResults/RunFmsTreeMaker_16080002_9.root"
Queue

