Universe        = vanilla
Requirements    = (CPU_Speed >= 1)
Rank		= CPU_Speed
request_memory  = 1800M
request_cpus    = 1
Priority        = 4
GetEnv          = True
Input           = /dev/null
when_to_transfer_output = ON_EXIT_OR_EVICT
+Experiment     = "star"
+Job_Type       = "cas"
Executable      = /star/u/kabir/GIT/BrightSTAR/jobs/test2/condor.sh
Initialdir      = /star/u/kabir/GIT/BrightSTAR/jobResults/test2/16081061
Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/081/16081061/st_fms_16081061_raw_2000028.MuDst.root	RunFmsRpTreeMaker_16081061_2000028.root"
Output          = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunFmsRpTreeMaker_16081061_2000028.out
Error           = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunFmsRpTreeMaker_16081061_2000028.err
Log             = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunFmsRpTreeMaker_16081061_2000028.log
Queue

Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/081/16081061/st_fms_16081061_raw_2500001.MuDst.root	RunFmsRpTreeMaker_16081061_2500001.root"
Output          = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunFmsRpTreeMaker_16081061_2500001.out
Error           = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunFmsRpTreeMaker_16081061_2500001.err
Log             = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunFmsRpTreeMaker_16081061_2500001.log
Queue

