// Filename: LinkDef.h
// Description: 
// Author: Latif Kabir < kabir@bnl.gov >
// Created: Mon Jul  1 13:52:59 2019 (-0400)
// URL: jlab.org/~latif

#ifdef __CINT__

//#pragma link C++ function FmsSimRunBfc;                        // Run BFC to convert simulated data to MuDst
#pragma link C++ function FmsSimRunJetMaker;                     // Run Fms Jet Maker for simulated data (Test Jet Maker)
#pragma link C++ function FmsSimRunStarsimAndBfc;                // Run Pythia + Geant3 (starsim) + BFC for FMS Jet Simulation
#pragma link C++ function ReadPythiaEvent;                       // Read Pythia Event tree (read example)
#pragma link C++ function ReadMuDstEvent;                        // Read MuDst generated by simulation (read example)
#pragma link C++ function FmsSimReadSimData;                     // Compare both pythia event and MuDst events (read example)
#pragma link C++ function FmsSimTreeMaker;                       // Combine MuDst nad Pythia info in same tree with event synchronization and trigger bit info
#pragma link C++ function FmsSimAnalyzeSimTree;                  // Analyze sim tree having MuDst and Pythia info combined to compare generated vs reconstructed photons
#pragma link C++ function RunFmsJetFinderPro;                    // Run FMS Jet Finder for Simulated Data (used for analysis)
#pragma link C++ function FmsSimJetQA;                           // Make QA plots for the FMS Jet from simulated data
#pragma link C++ function FmsSimCompareDataVsSim;                // Compare FMS simulation and data
#pragma link C++ function FmsSimCompareDataVsSimMatchDataToSim;  // Compare FMS simulation and data by matching data #events to that of sim pt
#pragma link C++ function FmsSimGenVsRecPion;                    // Compare FMS simulation and data for pion mass
#pragma link C++ function FmsSimMakeResponseMatrix;              // Generate Response Matrix or 2D hist for particle vs detector level quantities

#pragma link C++ function EEmcSimRunStarsimAndBfc;                // Run Pythia + Geant3 (starsim) + BFC for EEMC Jet Simulation
#pragma link C++ function RunEEmcJetFinderPro;                    // Run EEMC Jet Finder for Simulated Data (used for analysis)

#endif

