// Filename: LinkDef.h
// Description: 
// Author: Latif Kabir < kabir@bnl.gov >
// Created: Mon Jul  1 13:52:59 2019 (-0400)
// URL: jlab.org/~latif

#ifdef __CINT__

//#pragma link C++ function FmsSimRunBfc;                        // Run BFC to convert simulated data to MuDst
#pragma link C++ function FmsSimRunJetMaker;                     // Run Fms Jet Maker for simulated data
#pragma link C++ function FmsSimRunStarsimAndBfc;                // Run Pythia + Geant3 (starsim) + BFC for FMS Jet Simulation
#pragma link C++ function ReadPythiaEvent;                       // Read Pythia Event tree
#pragma link C++ function ReadMuDstEvent;                        // Read MuDst generated by simulation
#pragma link C++ function FmsSimReadSimData;                     // Compare both pythia event and MuDst events
#pragma link C++ function FmsSimTreeMaker;                       // Combine MuDst nad Pythia info in same tree
#pragma link C++ function RunFmsJetFinderPro;                    // Run FMS Jet Finder for Simulated Data
#pragma link C++ function FmsSimJetQA;                           // Make QA plots for the FMS Jet from simulated data
#pragma link C++ function FmsSimCompareDataVsSim;                // Compare FMS simulation and data

#endif

