Universe        = vanilla
Requirements    = (CPU_Speed >= 1)
Rank		= CPU_Speed
request_memory  = 1800M
request_cpus    = 1
Priority        = 4
GetEnv          = True
Input           = /dev/null
when_to_transfer_output = ON_EXIT_OR_EVICT
+Experiment     = "star"
+Job_Type       = "cas"
Executable      = /star/u/kabir/GIT/BrightSTAR/jobs/testRpEmc/condor.sh
Initialdir      = /star/u/kabir/GIT/BrightSTAR/dst/testRpEmc/16078040
Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P16id/2015/078/16078040/st_physics_16078040_raw_1000039.MuDst.root	AnRunEEmcRpTreeMakerPart1_16078040_1000039.root"
Output          = /star/u/kabir/GIT/BrightSTAR/jobOutput/AnRunEEmcRpTreeMakerPart1_16078040_1000039.out
Error           = /star/u/kabir/GIT/BrightSTAR/jobOutput/AnRunEEmcRpTreeMakerPart1_16078040_1000039.err
Log             = /star/u/kabir/GIT/BrightSTAR/jobOutput/AnRunEEmcRpTreeMakerPart1_16078040_1000039.log
Queue

