Universe        = vanilla
Requirements    = (CPU_Speed >= 1)
Rank		= CPU_Speed
request_memory  = 1800M
request_cpus    = 1
Priority        = 4
GetEnv          = True
Input           = /dev/null
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
+Experiment     = "star"
+Job_Type       = "cas"
transfer_input_files =   /star/u/kabir/GIT/BrightSTAR/.sl73_gcc485, /star/u/kabir/GIT/BrightSTAR/lib, /star/u/kabir/GIT/BrightSTAR/rootlogon.C, /star/u/kabir/GIT/BrightSTAR/setup.sh, /star/u/kabir/GIT/BrightSTAR/setup.csh, /star/u/kabir/GIT/BrightSTAR/config, /star/u/kabir/GIT/BrightSTAR/database
Executable      = /star/u/kabir/GIT/BrightSTAR/jobs/condor/condor.sh
Initialdir      = /star/u/kabir/GIT/BrightSTAR/scratch/condor/16066033
Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/066/16066033/st_fms_16066033_raw_0000005.MuDst.root	RunEmJetTreeMaker_16066033_0000005.root"
Output          = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunEmJetTreeMaker_16066033_0000005.out
Error           = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunEmJetTreeMaker_16066033_0000005.err
Log             = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunEmJetTreeMaker_16066033_0000005.log
Queue

