Universe        = vanilla
Requirements    = (CPU_Speed >= 1)
Rank		= CPU_Speed
request_memory  = 1800M
request_cpus    = 1
Priority        = 4
GetEnv          = True
#Input           = /dev/null
Input           = /star/u/kabir/GIT/BrightSTAR/FmsGainCorr.txt
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
Initialdir      = /star/u/kabir/GIT/BrightSTAR/scratch/EjAnalysisTreeQaR15Pass4EEmc/
Executable       =  /bin/bash
Output          = /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/jobOutput/EjAnalysisTreeQaR15Pass4EEmc$(Process).out
Error           = /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/jobOutput/EjAnalysisTreeQaR15Pass4EEmc$(Process).err
Log             = /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/jobOutput/EjAnalysisTreeQaR15Pass4EEmc$(Process).log
Arguments   =  "-c 'source /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/setup.sh && echo ""EjAnalysisTreeQa(\""/star/u/kabir/GIT/BrightSTAR/dst/emJet/run15/pass4/eemcTow/NanoJetTree_EjRunEmJetTreeMaker_16066033.root\"",\""EjAnalysisTreeQaR15Pass4EEmc_16066033.root\"",\""eemc\"")"" | root4star -l -b /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/rootlogon.C '"
Queue

