Universe        = vanilla
Requirements    = (CPU_Speed >= 1)
Rank		= CPU_Speed
request_memory  = 7200M
request_disk    = 8000M
request_cpus    = 1
Priority        = 4
GetEnv          = True
Input           = /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/starSim/lhapdf
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
+Experiment     = "star"
+Job_Type       = "cas"
transfer_input_files =   /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/.sl73_x8664_gcc485, /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/lib, /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/rootlogon.C, /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/setup.sh, /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/setup.csh, /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/config, /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/database, /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/vertex.txt
Executable      = /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/starSim/simJobs/condor.sh
Initialdir      = /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/scratch/condor/
Output          = /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/jobOutput/FmsSimPro$(Process).out
Error           = /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/jobOutput/FmsSimPro$(Process).err
Log             = /star/u/kabir/GIT/EmJet-GPC-BrightSTAR/jobOutput/FmsSimPro$(Process).log

Arguments       = $(Process) 10 	
Queue 2

