Universe        = vanilla
Requirements    = (CPU_Speed >= 1)
Rank		= CPU_Speed
request_memory  = 1800M
request_cpus    = 1
Priority        = 4
GetEnv          = True
Input           = /dev/null
when_to_transfer_output = ON_EXIT_OR_EVICT
+Experiment     = "star"
+Job_Type       = "cas"
Executable      = /star/u/kabir/GIT/BrightSTAR/jobs/test/condor.sh
Initialdir      = /star/u/kabir/GIT/BrightSTAR/jobResults/test/
Arguments       = "root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P15ik/2015/079/16079023/st_fms_16079023_raw_1000002.MuDst.root	RunFmsRpTreeMaker_16079023_1000002.root"
Output          = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunFmsRpTreeMaker_16079023_1000002.out
Error           = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunFmsRpTreeMaker_16079023_1000002.err
Log             = /star/u/kabir/GIT/BrightSTAR/jobOutput/RunFmsRpTreeMaker_16079023_1000002.log
Queue

